class Proyecto:
    def agregar_tarea(self, t): ...
    def calcular_avance(self): ...
    def listar_tareas(self): ...

class ReporteProyecto:
    def enviar_email_reporte(self, proyecto, email): ...

class RepositorioProyecto:
    def guardar_en_archivo(self, proyecto, ruta): ...
    def conectarse_a_base_de_datos(self): ...